[package]
name = "flatppl-python"
description = "Python modules and JAX callables backed by the FlatPPL compiler."
version = "0.1.0"
edition = "2024"
rust-version = "1.96"
license = "MIT"
repository = "https://github.com/flatppl/flatppl-python"

[lib]
name = "flatppl_python"
crate-type = ["rlib", "cdylib"]

[features]
extension = ["dep:pyo3", "dep:flatppl-python-api", "flatppl-python-api/extension"]

[dependencies]
flatppl-python-api = { git = "https://github.com/flatppl/flatppl-rust", rev = "e590dff21c0068a33f502cb991bce9a72609ca6a", optional = true }
pyo3 = { version = "0.29", optional = true }

[profile.release]
strip = true
lto = "thin"
codegen-units = 1
